/// System headers
#include <cstdio>   /// std::snprintf
/// Library headers
#include "Assert/RuntimeAssert.hpp"
#include "FileSystem/FileName.hpp"
#include "FileSystem/NativeFile.hpp"
#include "FileSystem/NativeWriteStream.hpp"
#include "Render/IndexedTriangle.hpp"
#include "Render/RenderMesh.hpp"
#include "Render/VertexDataType.hpp"
#include "Render/VertexLayout/Layout_Pos.hpp"
#include "Render/VertexLayout/Layout_Pos_Colr.hpp"
#include "Render/VertexLayout/Layout_Pos_Colr_Norm.hpp"
#include "Render/VertexLayout/Layout_Pos_Colr_Norm_Uv.hpp"
#include "Render/VertexLayout/Layout_Pos_Colr_Uv.hpp"
#include "Render/VertexLayout/Layout_Pos_Uv.hpp"
/// Self header
#include "IO/MeshFile/PlyFile.hpp"


static constexpr char BLANK[] = " ";
static constexpr char COMMENT_TOKEN_NAME     [] = "comment";
static constexpr char DATA_SEPARATOR         [] = "    ";
static constexpr char ELEMENT_TOKEN_NAME     [] = "element";
static constexpr char FACE_TOKEN_NAME        [] = "face";
static constexpr char HEADER_END_MARK        [] = "end_header";
static constexpr char LIST_TOKEN_NAME        [] = "list";
static constexpr char PROPERTY_TOKEN_NAME    [] = "property";
static constexpr char VERTEX_TOKEN_NAME      [] = "vertex";
static constexpr char VERTEX_INDEX_TOKEN_NAME[] = "vertex_indices";
/// 数据类型定义:
///static constexpr char CHAR_TYPE_TOKEN_NAME  [] = "char";
static constexpr char UCHAR_TYPE_TOKEN_NAME [] = "uchar";
///static constexpr char SINT16_TYPE_TOKEN_NAME[] = "short";
///static constexpr char UINT16_TYPE_TOKEN_NAME[] = "ushort";
static constexpr char SINT32_TYPE_TOKEN_NAME[] = "int";
///static constexpr char UINT32_TYPE_TOKEN_NAME[] = "uint";
static constexpr char FLOAT_TYPE_TOKEN_NAME [] = "float";
///static constexpr char DOUBLE_TYPE_TOKEN_NAME[] = "double";
/// 语义名称
static constexpr char POSITION_X_TOKEN_NAME [] = "x";   /// Pos:(x, y, z)
static constexpr char POSITION_Y_TOKEN_NAME [] = "y";
static constexpr char POSITION_Z_TOKEN_NAME [] = "z";
static constexpr char NORMAL_X_TOKEN_NAME   [] = "nx";  /// Normal:(x, y, z)
static constexpr char NORMAL_Y_TOKEN_NAME   [] = "ny";
static constexpr char NORMAL_Z_TOKEN_NAME   [] = "nz";
static constexpr char TEXTURE_U_TOKEN_NAME  [] = "s";   /// UV:(s, t)
static constexpr char TEXTURE_V_TOKEN_NAME  [] = "t";
static constexpr char COLOR_RED_TOKEN_NAME  [] = "red"; /// 顶点色彩(r, g, b, a)
static constexpr char COLOR_GREEN_TOKEN_NAME[] = "green";
static constexpr char COLOR_BLUE_TOKEN_NAME [] = "blue";
///static constexpr char COLOR_ALPHA_TOKEN_NAME[] = "alpha";


static
void
write_file_header (
    const RenderMesh &  mesh_data,
    NativeWriteStream & ply_file)
{
    char buffer[32];

    /// Magic number
    ply_file << "ply" << LINE_FEED;

    /// 输出文件格式
    ply_file << "format" << BLANK
             << "ascii"  << BLANK
             << "1.0"    << LINE_FEED;

    /// 输出Comment
    ply_file << COMMENT_TOKEN_NAME << BLANK
             << "--- PLY polygon exporter generated by RedSoUL ---" << LINE_FEED;

    /// 输出顶点数
    std::snprintf(buffer, sizeof(buffer), "%u", mesh_data.vertex_count);
    ply_file << ELEMENT_TOKEN_NAME << BLANK
             << VERTEX_TOKEN_NAME  << BLANK
             << buffer             << LINE_FEED;

    // --- 输出顶点定义 --- //
    /// 顶点定义排布图:
    /// +------------+---------+----------+------+
    /// | (POSITION) | (COLOR) | (NORMAL) | (UV) |
    /// +------------+---------+----------+------+
    ///
    /// NOTE: 通用的顶点语义数据:
    /// - x, y, z    <-- 位置
    /// - red, green, blue, alpha <-- 顶点色
    /// - nx, ny, nz <-- 法线
    /// - s, t       <-- 纹理坐标

    /// 位置数据声明
    ply_file << PROPERTY_TOKEN_NAME   << BLANK
             << FLOAT_TYPE_TOKEN_NAME << BLANK
             << POSITION_X_TOKEN_NAME << LINE_FEED;
    ply_file << PROPERTY_TOKEN_NAME   << BLANK
             << FLOAT_TYPE_TOKEN_NAME << BLANK
             << POSITION_Y_TOKEN_NAME << LINE_FEED;
    ply_file << PROPERTY_TOKEN_NAME   << BLANK
             << FLOAT_TYPE_TOKEN_NAME << BLANK
             << POSITION_Z_TOKEN_NAME << LINE_FEED;

    /// 顶点色彩数据声明
    if (mesh_data.vertex_layout & VertexDataType::COLOR_DATA)
    {
        ply_file << PROPERTY_TOKEN_NAME    << BLANK
                 << UCHAR_TYPE_TOKEN_NAME  << BLANK
                 << COLOR_RED_TOKEN_NAME   << LINE_FEED;
        ply_file << PROPERTY_TOKEN_NAME    << BLANK
                 << UCHAR_TYPE_TOKEN_NAME  << BLANK
                 << COLOR_GREEN_TOKEN_NAME << LINE_FEED;
        ply_file << PROPERTY_TOKEN_NAME    << BLANK
                 << UCHAR_TYPE_TOKEN_NAME  << BLANK
                 << COLOR_BLUE_TOKEN_NAME  << LINE_FEED;
    }

    /// 法线数据声明
    if (mesh_data.vertex_layout & VertexDataType::NORMAL_DATA)
    {
        ply_file << PROPERTY_TOKEN_NAME   << BLANK
                 << FLOAT_TYPE_TOKEN_NAME << BLANK
                 << NORMAL_X_TOKEN_NAME   << LINE_FEED;
        ply_file << PROPERTY_TOKEN_NAME   << BLANK
                 << FLOAT_TYPE_TOKEN_NAME << BLANK
                 << NORMAL_Y_TOKEN_NAME   << LINE_FEED;
        ply_file << PROPERTY_TOKEN_NAME   << BLANK
                 << FLOAT_TYPE_TOKEN_NAME << BLANK
                 << NORMAL_Z_TOKEN_NAME   << LINE_FEED;
    }

    /// 纹理坐标数据声明
    if (mesh_data.vertex_layout & VertexDataType::TEXCOORD_DATA)
    {
        ply_file << PROPERTY_TOKEN_NAME   << BLANK
                 << FLOAT_TYPE_TOKEN_NAME << BLANK
                 << TEXTURE_U_TOKEN_NAME  << LINE_FEED;
        ply_file << PROPERTY_TOKEN_NAME   << BLANK
                 << FLOAT_TYPE_TOKEN_NAME << BLANK
                 << TEXTURE_V_TOKEN_NAME  << LINE_FEED;
    }

    // --- 输出三角面定义 --- //
    /// 输出三角面数
    std::snprintf(buffer, sizeof(buffer), "%u", mesh_data.triangle_count);
    ply_file << ELEMENT_TOKEN_NAME << BLANK
             << FACE_TOKEN_NAME    << BLANK
             << buffer             << LINE_FEED;

    /// 输出Face类型声明:
    /// property list uchar int               vertex_indices
    ///          uchar列表  每个成员为int类型   列表名称
    ply_file << PROPERTY_TOKEN_NAME   << BLANK
             << LIST_TOKEN_NAME       << BLANK
             << UCHAR_TYPE_TOKEN_NAME << BLANK
             /// 列表中成员类型定义
             << SINT32_TYPE_TOKEN_NAME << BLANK /// NOTE: 索引数据类型必须为int32_t
             << VERTEX_INDEX_TOKEN_NAME << LINE_FEED;

    /// Header尾标记
    ply_file << HEADER_END_MARK << LINE_FEED;
}


static
void
write_position_data (
    const float_3       position,
    NativeWriteStream & ply_file,
    const char * const  separator)
{
    char buffer[128];
    std::snprintf(
        buffer, sizeof(buffer), "%+.6f  %+.6f  %+.6f",
        position.x, position.y, -position.z); /// 左手系--> 右手系: Z值取负, Z --> -Z
    ply_file << buffer << separator;
}


static
void
write_color_data (
    const float_3       color,
    NativeWriteStream & ply_file,
    const char * const  separator)
{
    char buffer[128];

    /// 将色彩从[0, 1]转换到[0, 255]
    const uint8_t red   = (uint8_t)(color.x * 255.99f);
    const uint8_t green = (uint8_t)(color.y * 255.99f);
    const uint8_t blue  = (uint8_t)(color.z * 255.99f);

    std::snprintf(
        buffer, sizeof(buffer), "%-3u  %-3u  %-3u", red, green, blue);
    ply_file << buffer << separator;
}


static
void
write_normal_data (
    const float_3       normal,
    NativeWriteStream & ply_file,
    const char * const  separator)
{
    char buffer[128];

    /// 左手系--> 右手系: Z值取负, Z --> -Z
    float_3 norm_rhs = float_3::make(normal.x, normal.y, -normal.z);
    norm_rhs.normalize();

    std::snprintf(
        buffer, sizeof(buffer), "%+.6f  %+.6f  %+.6f",
        norm_rhs.x, norm_rhs.y, norm_rhs.z);
    ply_file << buffer << separator;
}


static
void
write_texcoord_data (
    const float_2       texcoord,
    NativeWriteStream & ply_file,
    const char * const  separator)
{
    char buffer[128];
    std::snprintf(buffer, sizeof(buffer), "%+.4f  %+.4f", texcoord.x, texcoord.y);
    ply_file << buffer << separator;
}


static
void
write_vertices_data (
    const RenderMesh &  mesh_data,
    NativeWriteStream & ply_file)
{
    /// 为了迎合Maya
    /// - 我们将导出的几何数据以右手系表示(将顶点的Z值取负: Z --> -Z)
    /// - Y轴为竖直向上
    /// - UV坐标使用Bottom-Left方式(即, 原点在左下角)
    ///   TOP
    ///   ^ V
    ///   |
    ///   |
    ///   |
    ///   |
    ///   BOTTOM--------> U

    /// PLY文件中顶点数据流排布图:
    /// 
    /// +------------+----------+---------+---------+
    /// | (POSITION) | (NORMAL) |   (UV)  | (COLOR) |
    /// +------------+----------+---------+---------+

    /// 当前数据的偏移
    uint32_t data_offset = 0;
    switch (mesh_data.vertex_layout)
    {
        /// 只有Pos数据
        case Layout_Pos::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos & data =
                    *(const Layout_Pos*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos);
            }
            break;
        }

        /// Pos数据 + Color数据
        case Layout_Pos_Colr::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos_Colr & data =
                    *(const Layout_Pos_Colr*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, DATA_SEPARATOR);
                write_color_data(data.color, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos_Colr);
            }
            break;
        }

        /// Pos数据 + UV数据
        case Layout_Pos_Uv::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos_Uv & data =
                    *(const Layout_Pos_Uv*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, DATA_SEPARATOR);
                write_texcoord_data(data.texcoord, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos_Uv);
            }
            break;
        }

        /// Pos数据 + Color数据 + Normal数据
        case Layout_Pos_Colr_Norm::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos_Colr_Norm & data =
                    *(const Layout_Pos_Colr_Norm*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, DATA_SEPARATOR);
                write_color_data(data.color, ply_file, DATA_SEPARATOR);
                write_normal_data(data.normal, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos_Colr_Norm);
            }
            break;
        }

        /// Pos数据 + Color数据 + UV数据
        case Layout_Pos_Colr_Uv::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos_Colr_Uv & data =
                    *(const Layout_Pos_Colr_Uv*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, DATA_SEPARATOR);
                write_color_data(data.color, ply_file, DATA_SEPARATOR);
                write_texcoord_data(data.texcoord, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos_Colr_Uv);
            }
            break;
        }

        /// Pos数据 + Color数据 + Normal数据 + UV数据
        case Layout_Pos_Colr_Norm_Uv::LAYOUT_DECL:
        {
            for (uint32_t c = 0; c < mesh_data.vertex_count; ++c)
            {
                const Layout_Pos_Colr_Norm_Uv & data =
                    *(const Layout_Pos_Colr_Norm_Uv*)(mesh_data.vertex_list + data_offset);
                write_position_data(data.position, ply_file, DATA_SEPARATOR);
                write_color_data(data.color, ply_file, DATA_SEPARATOR);
                write_normal_data(data.normal, ply_file, DATA_SEPARATOR);
                write_texcoord_data(data.texcoord, ply_file, LINE_FEED);
                data_offset += sizeof(Layout_Pos_Colr_Norm_Uv);
            }
            break;
        }

        default:
        {
            RUNTIME_ASSERT(false, "Unknown Vertex Layout type!!");
            break;
        }
    }
}


static
void
write_face_indices_data (
    const RenderMesh &  mesh_data,
    NativeWriteStream & ply_file)
{
    /// 三角面中的顶点索引总数
    static constexpr uint8_t INDEX_COUNT = 3;

    char buffer[128];

    /// 由于PLY使用右手坐标系, 必须将Winding Order从顺时针 ---> 逆时针
    /// - <0, 1, 2> --> <0, 2, 1>
    for (uint32_t c = 0; c < mesh_data.triangle_count; ++c)
    {
        const IndexedTriangle & triangle_data = mesh_data.triangle_list[c];
        std::snprintf(
            buffer, sizeof(buffer), "%u    %u  %u  %u",
            INDEX_COUNT, triangle_data.idx_a, triangle_data.idx_c, triangle_data.idx_b);
        ply_file << buffer << LINE_FEED;
    }
}



bool
PlyFile::write_to (
    const char * const abs_file_name,
    const RenderMesh & mesh_data)
{
    RUNTIME_ASSERT( abs_file_name, "File name can not be NULL!!");
    RUNTIME_ASSERT(*abs_file_name, "File name can not be empty!!");

    char buffer[1024];

    /// 确保使用'.ply'文件扩展符
    FileName::append_file_extension(abs_file_name, "ply", buffer, sizeof(buffer));

    /// 创建WriteOnly文件流
    NativeWriteStream ply_file(buffer);
    if (ply_file.is_opened())
    {
        /// 输出文件头
        write_file_header(mesh_data, ply_file);
 
        /// 输出顶点数据
        write_vertices_data(mesh_data, ply_file);

        /// 输出Face顶点索引数据
        write_face_indices_data(mesh_data, ply_file);

        /// 关闭文件流
        ply_file.close();
        return true;
    }
    else
    {
        return false;
    }
}
