/// System headers
#include <cstdio>   /// std::snprintf
#include <cstring>  /// std::strlen, std::memcpy
/// Library headers
#include "Assert/RuntimeAssert.hpp"
#include "FileSystem/FileName.hpp"
#include "FileSystem/NativeFile.hpp"
#include "FileSystem/NativeWriteStream.hpp"
/// Self header
#include "IO/ImageFile/PpmFile.hpp"


/// PPM 文件定义:
/// https://en.wikipedia.org/wiki/Netpbm_format
///
/// PMM数据排布：
///
/// 上方------------ > 右侧
///  |
///  |
///  |
///  |
///  v
/// 底部


bool
PpmFile::write_to (
    const char * const    abs_file_name,
    const uint32_t        image_width,
    const uint32_t        image_height,
    const uint8_t * const data_start,
    const uint32_t        data_length,
    const bool            is_rgba_layout,
    const bool            use_alpha,
    const bool            use_binary)
{
    /// 每个Pixel的Channel数: Red, Green, Glue, Alpha Channels
    static constexpr uint8_t PIXEL_CHANNEL_COUNT = 4;
    /// 每个Channel所能表示的最大数值：(1 << 8) - 1: 255
    static constexpr uint32_t MAXIMAL_CHANNEL_VALUE = (1 << 8) - 1;

    RUNTIME_ASSERT( abs_file_name, "File name can not be NULL!!");
    RUNTIME_ASSERT(*abs_file_name, "File name can not be empty!!");

    char buffer[1024];

    /// 确保使用'.ppm'文件扩展符
    FileName::append_file_extension(abs_file_name, "ppm", buffer, sizeof(buffer));

    /// 创建WriteOnly文件流
    NativeWriteStream ppm_file(buffer);
    if (ppm_file.is_opened())
    {
        /// 输出Magic number
        if (use_binary)
        {
            ppm_file << "P6\n";
        }
        else
        {
            ppm_file << "P3\n";
        }

        /// 输出 Header
        ppm_file << "# --- PPM image exporter generated by RedSoUL ---\n\n"
                    "# PPM(Portable Pixel Map): 24bits RGB(RGB8)\n"
                    "# http://netpbm.sourceforge.net/doc/ppm.html\n"
                    "# Note :\n"
                    "# - the image data stored in the following way:\n"
                    "#  LEFT           RIGHT\n"
                    "#  TOP------------>\n"
                    "#   |\n"
                    "#   |\n"
                    "#   |\n"
                    "#   |\n"
                    "#   v\n"
                    "#  BOTTOM\n"
                    "#\n"
                    "# - RGB channels stored in this order: R G B\n";

        /// 输出图形的大小
        ppm_file << "# --- image dimension ---\n"
                    "# width in pixels(represented in decimal)\n";
        std::snprintf(buffer, sizeof(buffer), "%d", image_width);
        ppm_file << buffer << LINE_FEED;

        std::snprintf(buffer, sizeof(buffer), "%d", image_height);
        ppm_file << "# height in pixels(represented in decimal)\n";
        ppm_file << buffer << LINE_FEED;

        /// 输出数据的最大数值
        ppm_file << "# --- maximal image value in decimal\n";
        std::snprintf(buffer, sizeof(buffer), "%d", MAXIMAL_CHANNEL_VALUE);
        ppm_file << buffer << LINE_FEED;

        /// 输出图形数据
        /// NOTE: 由于PPM使用如下坐标系存储数据：
        ///
        /// 上方------------ > 右侧
        ///  |
        ///  |
        ///  |
        ///  |
        ///  v
        /// 底部
        ///
        /// NOTE: 在二进制格式中如果在Image Data前添加这一行, 会使图像显示错误
        if (!use_binary)
        {
            ppm_file << "# --- image data ---\n";
        }

        /// 所以我们首先输出最后一行的数据
        for (int32_t row = image_height - 1; row >= 0; --row)
        {
            for (uint32_t coln = 0; coln < image_width; ++coln)
            {
                const uint32_t data_offset =
                    (row * image_width + coln) * PIXEL_CHANNEL_COUNT;
                const uint8_t * const current_start = data_start + data_offset;
                const float alpha_value =
                    (float)current_start[3] / MAXIMAL_CHANNEL_VALUE;

                uint8_t red_value, green_value, blue_value;
                if (is_rgba_layout)
                {
                    /// RGBA存储格式
                    /// 低位             高位
                    /// +---+---+---+---+
                    /// | R | G | B | A |
                    /// +---+---+---+---+
                    red_value   = current_start[0];
                    green_value = current_start[1];
                    blue_value  = current_start[2];
                }
                else
                {
                    // BGRA存储格式
                    // 低位             高位
                    // +---+---+---+---+
                    // | B | G | R | A |
                    // +---+---+---+---+
                    red_value   = current_start[2];
                    green_value = current_start[1];
                    blue_value  = current_start[0];
                }

                if (use_alpha)
                {
                    red_value   = (uint8_t)(red_value   * alpha_value);
                    green_value = (uint8_t)(green_value * alpha_value);
                    blue_value  = (uint8_t)(blue_value  * alpha_value);
                }

                /// 以二进制形式输出
                if (use_binary)
                {
                    ppm_file << red_value;
                    ppm_file << green_value;
                    ppm_file << blue_value;
                }
                /// 以字符形式输出
                else
                {
                    std::snprintf(buffer, sizeof(buffer), "%-3d", red_value);
                    ppm_file << buffer << " ";
                    std::snprintf(buffer, sizeof(buffer), "%-3d", green_value);
                    ppm_file << buffer << " ";
                    std::snprintf(buffer, sizeof(buffer), "%-3d", blue_value);
                    ppm_file << buffer;

                    /// 输出完一个Pixel, 我们添加一些空格
                    if ((coln + 1) < image_width)
                    {
                        ppm_file << "    ";
                    }
                }
            }

            /// 输出完一行
            if (!use_binary)
            {
                ppm_file << LINE_FEED;
            }
        }

        /// 关闭文件流
        ppm_file.close();
        return true;
    }
    else
    {
        return false;
    }
}
