/// System headers
#include <cstdio> /// std::snprintf
/// Library headers
#include "Assert/RuntimeAssert.hpp"
#include "DataType/LdrColor.hpp"
#include "DataType/LdrGrayscale.hpp"
#include "FileSystem/FileName.hpp"
#include "FileSystem/NativeWriteStream.hpp"
#include "Math/EndianUtilities.hpp"
/// Self header
#include "IO/ImageFile/PpmFile.hpp"


// MARK:== PpmFileStream定义 == //
/// PPM 文件定义:
/// https://en.wikipedia.org/wiki/Netpbm_format
///
/// PMM数据排布：
///
/// 上方------------ > 右侧
///  |
///  |
///  |
///  |
///  v
/// 底部
struct PpmFileStream
{
    NativeWriteStream & ppm_stream;
    const bool          binary_ppm;

    PpmFileStream (
        NativeWriteStream & file_stream,
        const bool          use_binary)
    :
        ppm_stream(file_stream),
        binary_ppm(use_binary)
    {

    }

    void
    generate_file_header (
        const uint32_t image_width,
        const uint32_t image_height,
        const uint32_t maximal_value)
    {
        char buffer[128];

        /// 输出Magic number
        if (binary_ppm)
        {
            ppm_stream << "P6\n";
        }
        else
        {
            ppm_stream << "P3\n";
        }

        /// 输出 Header
        ppm_stream << "# --- PPM image exporter generated by RedSoUL ---\n\n"
                      "# PPM(Portable Pixel Map): ";
        ppm_stream << (maximal_value > 255 ? "48bits RGB(RGB16)\n" : "24bits RGB(RGB8)\n");
        ppm_stream << "# http://netpbm.sourceforge.net/doc/ppm.html\n"
                      "# Note :\n"
                      "# - the image data stored in the following way:\n"
                      "#  LEFT           RIGHT\n"
                      "#  TOP------------>\n"
                      "#   |\n"
                      "#   |\n"
                      "#   |\n"
                      "#   |\n"
                      "#   v\n"
                      "#  BOTTOM\n"
                      "#\n"
                      "# - RGB channels stored in this order: R G B\n";

        /// 输出图形的大小
        ppm_stream << "# --- image dimension ---\n"
                      "# width in pixels(represented in decimal)\n";
        std::snprintf(buffer, sizeof(buffer), "%u", image_width);
        ppm_stream << buffer << LINE_FEED;

        std::snprintf(buffer, sizeof(buffer), "%u", image_height);
        ppm_stream << "# height in pixels(represented in decimal)\n";
        ppm_stream << buffer << LINE_FEED;

        /// 输出数据的最大数值
        ppm_stream << "# --- maximal image value in decimal\n";
        std::snprintf(buffer, sizeof(buffer), "%u", maximal_value);
        ppm_stream << buffer << LINE_FEED;

        /// 输出图形数据
        /// NOTE: 由于PPM使用如下坐标系存储数据：
        ///
        /// 上方------------ > 右侧
        ///  |
        ///  |
        ///  |
        ///  |
        ///  v
        /// 底部
        ///
        /// NOTE: 在二进制格式中如果在Image Data前添加这一行, 会使图像显示错误
        if (binary_ppm == false)
        {
            ppm_stream << "# --- image data ---\n";
        }
    }

    /// 输出一个Rgb Pixel色彩数据
    ///
    /// @param[in]  pixel_data
    ///     Pixel的色彩数据
    /// @param[in]  is_last_coln
    ///     标记是否为最后一列的Pixel数据
    void
    output_rgb_pixel_data (
        const LdrColor pixel_data,
        const bool     is_last_coln)
    {
        char buffer[128];

        /// 以二进制形式输出
        if (binary_ppm)
        {
            ppm_stream << pixel_data.r;
            ppm_stream << pixel_data.g;
            ppm_stream << pixel_data.b;
        }
        /// 以字符形式输出
        else
        {
            std::snprintf(buffer, sizeof(buffer), "%-3d", pixel_data.r);
            ppm_stream << buffer << " ";
            std::snprintf(buffer, sizeof(buffer), "%-3d", pixel_data.g);
            ppm_stream << buffer << " ";
            std::snprintf(buffer, sizeof(buffer), "%-3d", pixel_data.b);
            ppm_stream << buffer;

            if (is_last_coln)
            {
                /// 输出完一行
                ppm_stream << LINE_FEED;
            }
            else
            {
                /// 添加一些空格
                ppm_stream << "    ";
            }
        }
    }

    /// 输出一个Grayscale Pixel色彩数据
    /// 
    /// @param[in]  pixel_data
    ///     Pixel的色彩数据
    /// @param[in]  is_last_coln
    ///     标记是否为最后一列的Pixel数据
    void
    output_grayscale_pixel_data (
        const LdrGrayscale pixel_data,
        const bool         is_last_coln)
    {
        char buffer[128];

        /// 以二进制形式输出
        if (binary_ppm)
        {
            RUNTIME_ASSERT(EndianUtility::is_big_endian() == false,
                           "No implementation for Big-endian CPU!!");

            /// NOTE: 二进制Rgb16模式, 使用Big Endianess方式存储数据
            /// Gimp也是期待Big Endianess
            ///
            const uint16_t scale_big_endian =
                EndianUtility::swap_endian_16(pixel_data.s);
            ppm_stream << scale_big_endian; /// 红
            ppm_stream << scale_big_endian; /// 绿
            ppm_stream << scale_big_endian; /// 蓝
        }
        /// 以字符形式输出
        else
        {
            std::snprintf(buffer, sizeof(buffer), "%-5d", pixel_data.s);
            ppm_stream << buffer << " ";
            std::snprintf(buffer, sizeof(buffer), "%-5d", pixel_data.s);
            ppm_stream << buffer << " ";
            std::snprintf(buffer, sizeof(buffer), "%-5d", pixel_data.s);
            ppm_stream << buffer;

            if (is_last_coln)
            {
                /// 输出完一行
                ppm_stream << LINE_FEED;
            }
            else
            {
                /// 添加一些空格
                ppm_stream << "    ";
            }
        }
    }
};


// MARK:== PpmFile定义 == //
bool
PpmFile::write_to (
    const char * const     abs_file_name,
    const uint32_t         image_width,
    const uint32_t         image_height,
    const LdrColor * const pixel_array,
    const uint32_t         pixel_count,
    const bool             is_rgba_layout,
    const bool             use_alpha,
    const bool             use_binary)
{
    /// Rbg8 每个Channel所能表示的最大数值： (1 << 8)  - 1: 255
    static constexpr uint32_t MAXIMAL_CHANNEL_VALUE_RGB8 = (1 << 8) - 1;

    RUNTIME_ASSERT( abs_file_name, "File name can not be NULL!!");
    RUNTIME_ASSERT(*abs_file_name, "File name can not be empty!!");
    RUNTIME_ASSERT(image_width  > 0, "Zero image width!!");
    RUNTIME_ASSERT(image_height > 0, "Zero image height!!");
    RUNTIME_ASSERT(image_width  <= 4 * 1024 * 1024, "Image width is too large!!");
    RUNTIME_ASSERT(image_height <= 4 * 1024 * 1024, "Image height is too large!!");
    RUNTIME_ASSERT(pixel_array, "No pixel data!!");
    RUNTIME_ASSERT(pixel_count >= (image_width * image_height),
                   "No enough pixel data!! Expected #pixel: %u, but given #pixel: %u",
                   image_width * image_height, pixel_count);

    char buffer[1024];

    /// 确保使用'.ppm'文件扩展符
    FileName::append_file_extension(abs_file_name, "ppm", buffer, sizeof(buffer));

    /// 创建WriteOnly文件流
    NativeWriteStream ppm_file(buffer);
    if (ppm_file.is_opened())
    {
        PpmFileStream ppm_stream(ppm_file, use_binary);
        ppm_stream.generate_file_header(
            image_width, image_height, MAXIMAL_CHANNEL_VALUE_RGB8);

        /// 所以我们首先输出最后一行的数据
        for (int32_t row = image_height - 1; row >= 0; --row)
        {
            for (uint32_t coln = 0; coln < image_width; ++coln)
            {
                const LdrColor & pixel_data = pixel_array[row * image_width + coln];

                LdrColor output_pixel;
                if (is_rgba_layout)
                {
                    /// RGBA存储格式
                    /// 低位             高位
                    /// +---+---+---+---+
                    /// | R | G | B | A |
                    /// +---+---+---+---+
                    output_pixel = pixel_data;
                }
                else
                {
                    // BGRA存储格式
                    // 低位             高位
                    // +---+---+---+---+
                    // | B | G | R | A |
                    // +---+---+---+---+
                    output_pixel.r = pixel_data.b;
                    output_pixel.g = pixel_data.g;
                    output_pixel.b = pixel_data.r;
                }

                if (use_alpha)
                {
                    const float alpha =
                        (float)pixel_data.a / MAXIMAL_CHANNEL_VALUE_RGB8;

                    const float red   = (float)output_pixel.r * alpha + 0.5f;
                    const float green = (float)output_pixel.g * alpha + 0.5f;
                    const float blue  = (float)output_pixel.b * alpha + 0.5f;
                    output_pixel.r = (uint8_t)red;
                    output_pixel.g = (uint8_t)green;
                    output_pixel.b = (uint8_t)blue;
                }

                ppm_stream.output_rgb_pixel_data(
                    output_pixel, coln == (image_width - 1));
            }
        }

        /// 关闭文件流
        ppm_file.close();
        return true;
    }
    else
    {
        return false;
    }
}


bool
PpmFile::write_to (
    const char * const         abs_file_name,
    const uint32_t             image_width,
    const uint32_t             image_height,
    const LdrGrayscale * const pixel_array,
    const uint32_t             pixel_count,
    const bool                 use_binary)
{
    /// Rgb16 每个Channel所能表示的最大整数值: (1 << 16) - 1: 65535
    static constexpr uint32_t MAXIMAL_CHANNEL_VALUE_RGB16 = (1 << 16) - 1;

    RUNTIME_ASSERT( abs_file_name, "File name can not be NULL!!");
    RUNTIME_ASSERT(*abs_file_name, "File name can not be empty!!");
    RUNTIME_ASSERT(image_width  > 0, "Zero image width!!");
    RUNTIME_ASSERT(image_height > 0, "Zero image height!!");
    RUNTIME_ASSERT(image_width  <= 4 * 1024 * 1024, "Image width is too large!!");
    RUNTIME_ASSERT(image_height <= 4 * 1024 * 1024, "Image height is too large!!");
    RUNTIME_ASSERT(pixel_array, "No pixel data!!");
    RUNTIME_ASSERT(pixel_count >= (image_width * image_height),
                   "No enough pixel data!! Expected #pixel: %u, but given #pixel: %u",
                   image_width * image_height, pixel_count);

    char buffer[1024];

    /// 确保使用'.ppm'文件扩展符
    FileName::append_file_extension(abs_file_name, "ppm", buffer, sizeof(buffer));

    /// 创建WriteOnly文件流
    NativeWriteStream ppm_file(buffer);
    if (ppm_file.is_opened())
    {
        PpmFileStream ppm_stream(ppm_file, use_binary);
        ppm_stream.generate_file_header(
            image_width, image_height, MAXIMAL_CHANNEL_VALUE_RGB16);

        /// 所以我们首先输出最后一行的数据
        for (int32_t row = image_height - 1; row >= 0; --row)
        {
            for (uint32_t coln = 0; coln < image_width; ++coln)
            {
                const LdrGrayscale & pixel_data = pixel_array[row * image_width + coln];
                ppm_stream.output_grayscale_pixel_data(
                    pixel_data, coln  == (image_width - 1));
            }
        }

        /// 关闭文件流
        ppm_file.close();
        return true;
    }
    else
    {
        return false;
    }
}
